[modules.AmazonChimeSDK]
imports = ["Foundation", "AVFoundation", "UIKit", "AmazonChimeSDKMedia"]
testableImports = ["AmazonChimeSDK"]
sources = [
    "AmazonChimeSDK/analytics/EventAnalyticsController.swift",
    "AmazonChimeSDK/analytics/EventAnalyticsObserver.swift",
    "AmazonChimeSDK/audiovideo/audio/activespeakerdetector/ActiveSpeakerDetectorFacade.swift",
    "AmazonChimeSDK/audiovideo/audio/scheduler/Scheduler.swift",
    "AmazonChimeSDK/audiovideo/AudioVideoControllerFacade.swift",
    "AmazonChimeSDK/audiovideo/AudioVideoObserver.swift",
    "AmazonChimeSDK/audiovideo/contentshare/ContentShareController.swift",
    "AmazonChimeSDK/audiovideo/contentshare/ContentShareObserver.swift",
    "AmazonChimeSDK/audiovideo/metric/MetricsObserver.swift",
    "AmazonChimeSDK/audiovideo/video/capture/CameraCaptureSource.swift",
    "AmazonChimeSDK/audiovideo/video/capture/CaptureSourceObserver.swift",
    "AmazonChimeSDK/audiovideo/video/VideoRenderView.swift",
    "AmazonChimeSDK/audiovideo/video/VideoSink.swift",
    "AmazonChimeSDK/audiovideo/video/VideoSource.swift",
    "AmazonChimeSDK/audiovideo/video/VideoTileController.swift",
    "AmazonChimeSDK/audiovideo/video/VideoTileControllerFacade.swift",
    "AmazonChimeSDK/audiovideo/video/capture/VideoCaptureSource.swift",
    "AmazonChimeSDK/device/DeviceController.swift",
    "AmazonChimeSDK/ingestion/AppStateMonitor.swift",
    "AmazonChimeSDK/ingestion/AppStateMonitorDelegate.swift",
    "AmazonChimeSDK/ingestion/EventBuffer.swift",
    "AmazonChimeSDK/ingestion/EventReporter.swift",
    "AmazonChimeSDK/ingestion/EventSender.swift",
    "AmazonChimeSDK/ingestion/IngestionEventConverter.swift",
    "AmazonChimeSDK/internal/analytics/MeetingStatsCollector.swift",
    "AmazonChimeSDK/internal/audio/protocols/AudioClientController.swift",
    "AmazonChimeSDK/internal/audio/protocols/AudioClientObserver.swift",
    "AmazonChimeSDK/internal/audio/protocols/AudioClientProtocol.swift",
    "AmazonChimeSDK/internal/audio/protocols/AudioLock.swift",
    "AmazonChimeSDK/internal/audio/protocols/AudioSession.swift",
    "AmazonChimeSDK/internal/contentshare/ContentShareVideoClientController.swift",
    "AmazonChimeSDK/internal/ingestion/database/DatabaseClient.swift",
    "AmazonChimeSDK/internal/ingestion/database/DatabaseManager.swift",
    "AmazonChimeSDK/internal/ingestion/DirtyEventDao.swift",
    "AmazonChimeSDK/internal/ingestion/EventDao.swift",
    "AmazonChimeSDK/internal/metric/ClientMetricsCollector.swift",
    "AmazonChimeSDK/internal/video/VideoClientController.swift",
    "AmazonChimeSDK/internal/video/VideoClientProtocol.swift",
    "AmazonChimeSDK/realtime/RealtimeControllerFacade.swift",
    "AmazonChimeSDK/realtime/RealtimeObserver.swift",
    "AmazonChimeSDK/realtime/TranscriptEventObserver.swift",
    "AmazonChimeSDK/session/CreateAttendeeResponse.swift",
    "AmazonChimeSDK/session/CreateMeetingResponse.swift",
    "AmazonChimeSDK/session/MeetingSessionConfiguration.swift",
    "AmazonChimeSDK/utils/logger/Logger.swift",
]
output = "AmazonChimeSDKCuckooTests/Generated/GeneratedMocks.swift"

[modules.AmazonChimeSDK.options]
keepDocumentation = false
