# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AmazonChimeSDKDemoPods' do
  use_frameworks!
  # Pods for AmazonChimeSDKDemoPods
  pod 'AmazonChimeSDK-Bitcode', '0.19.3'
end

target 'AmazonChimeSDKDemoBroadcastPods' do
  use_frameworks!
  # Pods for AmazonChimeSDKDemoBroadcastPods
  pod 'AmazonChimeSDK-Bitcode', '0.19.3'
end
